### ISSUE TITLE
Error con imagemin  

### ISSUE THREAD

**Issue by apaz074** [jonmircha/kenai-npm-starter-kit#1]
Al tratar de usar el comando imagen me da el siguiente error con las imagenes png:

 kenai-npm-starter-kit@1.0.0 imagemin /mnt/Desarrollo/pruebas/kenai-npm-starter-kit-master
> imagemin "./src/img/**.+(jpg|png)" -o ./public/img/ -p=pngquant -p=jpeg-recompress

Error: Error in file: ./src/img/indicator-pug.png

/mnt/Desarrollo/pruebas/kenai-npm-starter-kit-master/node_modules/pngquant-bin/vendor/pngquant: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

    at Promise.all.then.arr (/mnt/Desarrollo/pruebas/kenai-npm-starter-kit-master/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kenai-npm-starter-kit@1.0.0 imagemin: `imagemin "./src/img/**.+(jpg|png)" -o ./public/img/ -p=pngquant -p=jpeg-recompress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kenai-npm-starter-kit@1.0.0 imagemin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/apaz/.npm/_logs/2018-02-19T04_23_53_075Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kenai-npm-starter-kit@1.0.0 assets: `npm run statics && npm run imagemin && npm run webp && npm run svgmin && npm run gifmin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kenai-npm-starter-kit@1.0.0 assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/apaz/.npm/_logs/2018-02-19T04_23_53_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kenai-npm-starter-kit@1.0.0 build: `npm run assets && npm run min && npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kenai-npm-starter-kit@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Una idea de como solucionarlo?

**Comment by JulioLopez73** [comment]
Hola si estas trabajando con ubuntu 16 o superior, necesitas una librería que ya no está disponible.
Tendrías que descargarte la siguiente librería:
 https://packages.ubuntu.com/xenial/amd64/libpng12-0/download
y despues la instalas con;

sudo dpkg -i libpng12-0_1.2.54-1ubuntu1.1_amd64.deb

También puede ser que necesites de la siguiente librería.

sudo apt install libjpeg62

Yo he solucionado el problema instalando esas dos librerías.

**Comment by jonmircha** [comment]
Gracias por el dato 👍

**Comment by JulioLopez73** [comment]
Nada Jon, un placer, gracias a ti por hacer el kit que nos ayuda muchísimo en rapidez y adentrarnos un poco mas al tema de los componentes.

**Comment by JulioLopez73** [comment]
Nada Jon, es un placer poder ayudar.
